### ISSUE TITLE
Crashes on var = delayObject line

### ISSUE THREAD

**Issue by thijsheijden** [kiritmodi2702/GIF-Swift#5]
Sometimes when loading loading gifs using `Uiimage.gifImageWithUrl()` the app will crash on the 

`var delayObject: AnyObject = unsafeBitCast(CFDictionaryGetValue(gifProperties, Unmanaged.passUnretained(kCGImagePropertyGIFUnclampedDelayTime).toOpaque()), to: AnyObject.self)`

Which is line 59 in the file.

Please help me, I have tried multiple fixes but none worked haha. I think it has something to do with Gifs having only 1 frame?

**Comment by nimishanumbertank** [comment]
I am facing similar issue.

**Comment by thijsheijden** [comment]
I figured out that it was because gifProperties was nil, so I just wrote a simple if statement checking if gifProperties != nil so that every time it was nil the gif would not be added. After doing this the error never happened again.

**Comment by nimishanumbertank** [comment]
In my case, i have added if condition but sometimes its still crashing my app.
