### ISSUE TITLE
How to load GIF Image once

### ISSUE THREAD

**Issue by ghost** [kiritmodi2702/GIF-Swift#6]
I want to show GIF only once. I mean it should not repeat.
How should i do that by using this ?

**Comment by kiritmodi2702** [comment]
> I want to show GIF only once. I mean it should not repeat.
> How should i do that by using this ?

GIF image is continue run. But you can split the GIF image in the number of images, And animate within  particular second.

    let myimgArr = ["1.jpg","2.jpg","3.jpg"]
    var images = [UIImage]()
    for i in 0..<myimgArr.count
    {
        images.append(UIImage(named: myimgArr[i])!)
    }

    imgView_ref.animationImages = images
    imgView_ref.animationDuration = 0.04
    imgView_ref.animationRepeatCount = 2
    imgView_ref.startAnimating()
